# Generated by Django 6.0.3 on 2026-03-24 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre o Razón Social')),
                ('ruc_cedula', models.CharField(max_length=20, unique=True, verbose_name='RUC/Cédula')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('un', 'Unidades'), ('m', 'Metros'), ('kg', 'Kilogramos'), ('l', 'Litros'), ('p2', 'Pies Tablares'), ('par', 'Pares (Correderas)'), ('m2', 'Metros Cuadrados')], default='un', max_length=5)),
                ('precio_referencia', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('precio_venta', models.DecimalField(decimal_places=0, max_digits=12)),
                ('costo_placa_entera', models.DecimalField(decimal_places=0, max_digits=12)),
                ('ancho_placa_cm', models.FloatField(default=183)),
                ('largo_placa_cm', models.FloatField(default=260)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='muebles/')),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_corte', 'En Corte'), ('en_taller', 'En Taller'), ('en_armado', 'En Armado'), ('listo', 'Listo para Entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('tipo_pedido', models.CharField(choices=[('cliente', 'Venta Directa'), ('stock', 'Producción de Sobrante (Stock)')], default='cliente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='inventario.cliente')),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.mueble')),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('largo', models.FloatField(help_text='Sentido de la veta (cm)')),
                ('ancho', models.FloatField(help_text='Ancho (cm)')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mueble')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1.0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mueble')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('corte', 'Corte de Placas'), ('canteado', 'Pegado de Cantos'), ('armado', 'Armado de Estructura'), ('terminacion', 'Lustre y Limpieza')], max_length=50)),
                ('completada', models.BooleanField(default=False, verbose_name='¿Terminado?')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='inventario.pedido')),
            ],
        ),
    ]
