# Generated by Django 6.0.3 on 2026-03-31 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('ruc_cedula', models.CharField(max_length=20, unique=True, verbose_name='RUC o Cédula')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('barrio', models.CharField(max_length=100, verbose_name='Barrio')),
                ('calle_principal', models.CharField(max_length=150, verbose_name='Calle Principal')),
                ('numero_casa', models.CharField(max_length=20, verbose_name='N° de Casa')),
                ('calle_lateral_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Calle Lateral 1')),
                ('calle_lateral_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Calle Lateral 2')),
                ('referencia_ubicacion', models.TextField(blank=True, null=True, verbose_name='Referencia de Ubicación')),
                ('geolocalizacion', models.URLField(blank=True, help_text='Pega aquí el enlace de Google Maps (URL)', null=True, verbose_name='Enlace Google Maps')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('un', 'Unidades'), ('m', 'Metros'), ('kg', 'Kilogramos'), ('l', 'Litros'), ('p2', 'Pies Tablares'), ('par', 'Pares'), ('m2', 'Metros Cuadrados')], default='un', max_length=5)),
                ('precio_referencia', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('precio_venta', models.DecimalField(decimal_places=0, max_digits=12)),
                ('costo_placa_entera', models.DecimalField(decimal_places=0, max_digits=12)),
                ('ancho_placa_cm', models.FloatField(default=183)),
                ('largo_placa_cm', models.FloatField(default=260)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FotoMueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='muebles/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.mueble')),
            ],
            options={
                'verbose_name': 'Foto de detalle',
                'verbose_name_plural': 'Fotos de detalles',
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('largo', models.FloatField(help_text='Sentido de la veta (cm)')),
                ('ancho', models.FloatField(help_text='Ancho (cm)')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mueble')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1.0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mueble')),
            ],
        ),
    ]
