# Generated by Django 6.0.3 on 2026-03-14 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('un', 'Unidades (Global)'), ('m', 'Metros'), ('kg', 'Kilogramos')], default='un', max_length=5)),
                ('precio_referencia', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('precio_venta', models.DecimalField(decimal_places=0, max_digits=12)),
                ('costo_placa_madera', models.DecimalField(decimal_places=0, max_digits=12)),
                ('ancho_total_madera', models.FloatField(help_text='Ancho necesario en cm')),
                ('largo_total_madera', models.FloatField(help_text='Largo necesario en cm')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='muebles/')),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_corte', 'En Corte'), ('en_armado', 'En Taller'), ('listo', 'Listo para Entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.mueble')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1.0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mueble')),
            ],
        ),
    ]
