# Generated by Django 6.0.3 on 2026-03-24 22:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='completada',
            new_name='terminado',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(choices=[('1_DISENO', '1. Diseño y Despiece'), ('2_SOLO_CORTE_EXT', '2. Pedido de SOLO CORTE (Externo)'), ('3_CORTE_CANTO_EXT', '3. Pedido de CORTE Y CANTEADO (Externo)'), ('4_RECEPCION', '4. Recepción de Placas en Taller'), ('5_CANTEADO_TALLER', '5. Canteado en Taller (Manual/Máquina)'), ('6_MECANIZADO', '6. Perforado (Bisagras/Minifix)'), ('7_ENSAMBLADO', '7. Ensamblado de Mueble'), ('8_HERRAJES', '8. Instalación de Herrajes'), ('9_LIMPIEZA', '9. Limpieza y Ajuste Final'), ('10_LISTO', '10. Listo para Entrega / Instalación')], default='1_DISENO', max_length=50),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tiempo',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc_cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('cliente', 'Venta Directa'), ('stock', 'Producción de Stock')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
