# Generated by Django 6.0.3 on 2026-03-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mueble',
            name='ancho_total_madera',
        ),
        migrations.RemoveField(
            model_name='mueble',
            name='costo_placa_madera',
        ),
        migrations.RemoveField(
            model_name='mueble',
            name='largo_total_madera',
        ),
        migrations.AddField(
            model_name='mueble',
            name='ancho_placa_cm',
            field=models.FloatField(default=183, help_text='Ancho de la placa (ej: 183)'),
        ),
        migrations.AddField(
            model_name='mueble',
            name='costo_placa_entera',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio de la placa completa', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mueble',
            name='largo_placa_cm',
            field=models.FloatField(default=260, help_text='Largo de la placa (ej: 260)'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('un', 'Unidades'), ('m', 'Metros'), ('kg', 'Kilogramos'), ('l', 'Litros'), ('p2', 'Pies Tablares'), ('par', 'Pares (Correderas)'), ('m2', 'Metros Cuadrados')], default='un', max_length=5),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cantidad',
            field=models.FloatField(default=1.0, help_text='Cantidad usada en este mueble'),
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Lateral, Puerta...', max_length=100)),
                ('largo', models.FloatField(help_text='Largo en cm')),
                ('ancho', models.FloatField(help_text='Ancho en cm')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('mueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mueble')),
            ],
        ),
    ]
