# Generated by Django 6.0.3 on 2026-03-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_completada_tarea_terminado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('un', 'Unidades'), ('m', 'Metros'), ('kg', 'Kilogramos'), ('l', 'Litros'), ('p2', 'Pies Tablares'), ('par', 'Pares'), ('m2', 'Metros Cuadrados')], default='un', max_length=5),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', '1. Pendiente'), ('produccion', '2. En Producción'), ('listo', '3. Listo para Entrega'), ('entregado', '4. Entregado'), ('cancelado', '5. Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(choices=[('1_DISENO', '1. Diseño y Despiece'), ('4_RECEPCION', '4. Recepción de Placas'), ('7_ENSAMBLADO', '7. Ensamblado de Mueble'), ('9_LIMPIEZA', '9. Limpieza y Ajuste Final'), ('10_LISTO', '10. Listo para Entrega / Instalación')], default='1_DISENO', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tiempo',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
