# Generated by Django 6.0.3 on 2026-03-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_mueble_ancho_total_madera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('cliente', 'Venta Directa'), ('stock', 'Producción de Sobrante (Stock)')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='ancho_placa_cm',
            field=models.FloatField(default=183),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='costo_placa_entera',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='largo_placa_cm',
            field=models.FloatField(default=260),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_corte', 'En Corte'), ('en_armado', 'En Taller'), ('listo', 'Listo para Entrega'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='ancho',
            field=models.FloatField(help_text='Ancho (cm)'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='largo',
            field=models.FloatField(help_text='Sentido de la veta (cm)'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cantidad',
            field=models.FloatField(default=1.0),
        ),
    ]
