# Generated by Django 6.0.3 on 2026-03-31 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('corte', models.BooleanField(default=False, verbose_name='Corte')),
                ('canteado', models.BooleanField(default=False, verbose_name='Canteado')),
                ('armado', models.BooleanField(default=False, verbose_name='Armado')),
                ('limpieza', models.BooleanField(default=False, verbose_name='Limpieza')),
                ('empaquetado', models.BooleanField(default=False, verbose_name='Empaquetado')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.pedido', verbose_name='Pedido Relacionado')),
                ('personal_asignado', models.ManyToManyField(to='inventario.personal', verbose_name='Personal Asignado')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
            },
        ),
    ]
