# Generated by Django 6.0.3 on 2026-03-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_insumo_unidad_medida_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_pedido',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(choices=[('1_DISENO', '1. Diseño y Despiece'), ('2_PRESUPUESTO', '2. Aprobación de Presupuesto'), ('3_PEDIDO_CORTE', '3. Pago y Pedido a Maderera'), ('4_PROCESO_MADERERA', '4. Corte y Canteado Externo'), ('5_RECEPCION', '5. Recepción de Piezas en Taller'), ('6_ARMADO', '6. Ensamblado y Herrajes'), ('7_INSTALACION', '7. Instalación en Obra'), ('8_LIMPIEZA', '8. Limpieza y Ajuste Final'), ('9_LISTO', '9. Finalizado para Entrega')], default='1_DISENO', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tiempo',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
