# Generated by Django 6.0.3 on 2026-04-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_personal_ordentrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='apellido',
            field=models.CharField(default=1, max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='personal',
            name='ruc_cedula',
            field=models.CharField(default='0', max_length=20, unique=True, verbose_name='RUC o Cédula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='especialidad',
            field=models.CharField(default='sin escialidad', max_length=100, verbose_name='Especialidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
