# Generated by Django 6.0.3 on 2026-03-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_pedido_tipo_pedido_alter_mueble_ancho_placa_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_corte', 'En Corte'), ('en_taller', 'En Taller'), ('en_armado', 'En Armado'), ('listo', 'Listo para Entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
