# Generated by Django 6.0.3 on 2026-04-15 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_personal_apellido_personal_direccion_personal_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='¿Orden Terminada?'),
        ),
        migrations.AddField(
            model_name='personal',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio'),
        ),
    ]
