# Generated by Django 6.0.3 on 2026-04-28 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_ordentrabajo_fecha_fin_ordentrabajo_finalizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ruc_cedula',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='ruc_cedula',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='personal',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='personal',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='geolocalizacion',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace Google Maps'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
