# Generated by Django 6.0.3 on 2026-05-11 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_cliente_ruc_cedula_remove_personal_ruc_cedula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotomueble',
            options={},
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], default='pendiente', max_length=15, verbose_name='Estado del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mueble', verbose_name='Mueble'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
    ]
