# Generated by Django 6.0.3 on 2026-05-11 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_pedido_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('nro_factura', models.CharField(max_length=20, unique=True, verbose_name='Número de Factura')),
                ('condicion_venta', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10, verbose_name='Condición')),
                ('cliente_nombre', models.CharField(editable=False, max_length=200)),
                ('cliente_ruc', models.CharField(editable=False, max_length=20)),
                ('mueble_nombre', models.CharField(editable=False, max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio Unitario')),
                ('iva_10', models.DecimalField(decimal_places=0, editable=False, max_digits=12, verbose_name='IVA 10%')),
                ('total', models.DecimalField(decimal_places=0, editable=False, max_digits=12, verbose_name='Total Gs.')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.pedido', verbose_name='Pedido Relacionado')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
